### ISSUE TITLE
Microsites - sticky navigation not aligned correctly to the top of the page

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2317]
https://www.cancer.gov/pediatric-adult-rare-tumor/
https://www.cancer.gov/rare-brain-spine-tumor/
https://www.cancer.gov/nano/
https://dceg.cancer.gov/ (fix in #2316 now has DCEG looking like these others)

For the three microsites listed above, the main navigation is sticking to the top of the page when you scroll, but it's a bit cut off at the top (b/c of linkback?). 

<img width="1453" alt="Screen Shot 2019-08-09 at 4 25 25 PM" src="https://user-images.githubusercontent.com/29731392/62807025-55f43400-bac2-11e9-8997-97516414ccd4.png">

Also, when you then scroll back up the page a bit, the utility bar row is also cutting a bit cut off.

<img width="1346" alt="Screen Shot 2019-08-09 at 4 26 04 PM" src="https://user-images.githubusercontent.com/29731392/62807062-6dcbb800-bac2-11e9-8060-671a8e184c75.png">

**Comment by amydugan** [comment]
@arcepaul @markecramer - I am taking this ticket out of Digital Platform Release 1.1.5 since this is being addressed in DTM.

**Comment by markecramer** [comment]
I'm currently fixing DCEG, which will align it with the other 3 microsites. That is the Back to Top and DCEG nav disappearing will be fixed, but all 4 will still have the issue with the linkback sitting on top of the sticky nav. Once DCEG is resolved, I will then take a look at that issue and see if anything short of switching to the simpler version of the linkback (which we don't have approval for at this point) will work.

**Comment by markecramer** [comment]
We are testing out a temporary solution, on DCEG, the linkback will maintain current functionality, sticking to top of page, but disappearing when the page is scrolled down 50 pixels or more from top. It is available to test in DTM stage (dceg.cancer.gov, DTM extension set to stage).

**Comment by markecramer** [comment]
I've changed the point at which the linkback goes away from 99px down the screen to 20px.

**Comment by VictoriaSunNIH** [comment]
OBE with new design of linkback
