### ISSUE TITLE
User Unable to Save Spanish Content on Article Content Type

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#2457]
The user is unable to save Drupal updates to the 'Sintomas' article page after updating content in the body content block.

URL: https://www.cancer.gov/espanol/cancer/diagnostico-estadificacion/sintomas

![image](https://user-images.githubusercontent.com/22639543/65705481-87b36100-e056-11e9-9d7c-20ec67882e9f.png)

**Comment by sarinapadilla** [comment]
Not sure who did it, but this issue has been fixed on Prod: every article has been pushed through the workflow, and therefore the correct value for the schema_org_data field has been saved for all of the nodes.

I believe an edge case that could bring up this issue again is if a Spanish page is created before its English translation. I have written a script (tested locally, but never run against a Prod database backup) to update the values for schema_org_data in the database.

[update-schema-org-data.txt](https://github.com/NCIOCPL/cgov-digital-platform/files/3691391/update-schema-org-data.txt)

**Comment by adriancofie** [comment]
Re-opening as per slack 10/7 convo: https://ncisape.slack.com/archives/CDTLCJ9DJ/p1570471081136100

This is still an issue for some items, and it's happening for microsites as well.
